id: P007905
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24886
  title: ལྷོ་ཁའི་དམངས་རྩོམ་ལེགས་བཏུས་བྱིས་པ་དགའ་བའི་གཏམ།
  author: ''
  volumes:
    bb8bfa13078141d8bc0126af73913b1f:
      image_group_id: I1KG24888
      title: ''
      volume_number: 1
      total_pages: 356
ebook_metadata:
  title: ལྷོ་ཁའི་དམངས་རྩོམ་ལེགས་བཏུས་བྱིས་པ་དགའ་བའི་གཏམ།
  author: ''
  sku: P007905
  cover: cover.jpg
  layers:
  - pagination
