id: P007905
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG24886
  title: ལྷོ་ཁའི་དམངས་རྩོམ་ལེགས་བཏུས་བྱིས་པ་དགའ་བའི་གཏམ།
  author: ''
  volumes:
    a5b527e735ad4c2cafba318004b585fe:
      image_group_id: I1KG24888
      title: Volume 1 of lho kha'i dmangs rtsom legs btus byis pa dga' ba'i gtam/
      volume_number: 1
      total_pages: 356
      base_file: v001.txt
