id: opecha:P007905
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24886
  title: ལྷོ་ཁའི་དམངས་རྩོམ་ལེགས་བཏུས་བྱིས་པ་དགའ་བའི་གཏམ།
  volume:
    a5b527e735ad4c2cafba318004b585fe:
      image_group_id: I1KG24888
      title: Volume 1 of lho kha'i dmangs rtsom legs btus byis pa dga' ba'i gtam/
      volume_number: 1
      total_pages: 356
  author: ''
ebook_metadata:
  title: ལྷོ་ཁའི་དམངས་རྩོམ་ལེགས་བཏུས་བྱིས་པ་དགའ་བའི་གཏམ།
  author: ''
  sku: P007905
  cover: cover.jpg
  layers:
  - pagination
